@startuml

:mapperProxy;

note right
invok()
====
代理方法 最后是通过SqlSessionManage创建当前线程的SqlSession
然后调用SqlSession的方法
end note

:SqlSessionManage

: SqlSession;

note left
# 线程唯一 跟随线程
# SqlSessionManage -> SqlSessionFactory -> SqlSession
# 一个线程 -> 一个SqlSession
end note

: Executor ;

note right
执行器的基类, 装饰器模式 可以无限叠加功能
一个线程 -> 一个SqlSession -> 一个Executor
====
# BaseExecutor
# SimpleExecutor
end note


:ParamterHanler;
note right
参数处理器
====

end note

:ResultSetHandler;
note left
结果映射处理器
====

end note
@enduml