@startuml
:MapperAnotationBuilder类;

:Parse( ) ;

:parseStatement( );

:SqlSourceBuilder类;

:parse( );

note right
* 解析sql的#{xxx} MapperBuilderAssistant.parseMethodParameterMapping();
    * 获取参数名称
    * 获取javatype
    * 获取jdbctype
    * 获取javattype <-> jabctype 的 typehandler
    * 返回List<ParameterMapping>
* 添加参数映射
end note

:SqlSource (Inteface);

:AnnonationSqlSource ( Class) - implement -> Sqlsource ;



@enduml