server:
  port: 16000


eureka:
  instance:
    #主机ip
    hostname: 106.54.208.155
    hostport: 8500
    #server一定程度上也是client，互为client
  client:
    #由于自己就是服务器，不需要注册到自己
    registerWithEureka: true
    #由于自己就是服务器，不需要从服务器获取注册信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.hostport}/eureka/

spring:
  application:
    name: sanhuo-test
